"""
grpc_service/meal_server.py
============================
gRPC Server — Experiment 3: Distributed Computing

This server implements the MealService defined in:
    grpc_service/proto/meal_service.proto

Architecture:
  - Runs as a standalone process (separate from the Flask web app).
  - Listens on port 50051 for gRPC connections.
  - Loads meal nutrition data from the existing Dataset/ CSV files.
  - Demonstrates Lamport logical clock for distributed event ordering.

How gRPC works here:
  1. Client sends MealRequest (meal_name + Lamport timestamp).
  2. Server updates its Lamport clock:  max(server, client) + 1
  3. Server looks up nutrition in the datasets.
  4. Server ticks its Lamport clock for the response event.
  5. Server returns MealResponse (nutrition + server Lamport timestamp).
"""

from concurrent import futures
import os
import sys

# ============================================================
# RESOLVE PROJECT ROOT
# Add the project root to sys.path so we can import
# grpc_service.generated and grpc_service.lamport_clock
# correctly when running as:  python -m grpc_service.meal_server
# ============================================================

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)
sys.path.insert(0, PROJECT_ROOT)

# ============================================================
# IMPORT gRPC (from installed grpcio package — NOT local folder)
# ============================================================
import grpc                                                 # noqa: E402  (grpcio)
import pandas as pd                                         # noqa: E402

# ============================================================
# IMPORT GENERATED PROTOBUF STUBS
# These were generated by grpc_tools.protoc from meal_service.proto
# ============================================================
from grpc_service.generated import meal_service_pb2        # noqa: E402
from grpc_service.generated import meal_service_pb2_grpc   # noqa: E402

# ============================================================
# IMPORT LAMPORT CLOCK
# ============================================================
from grpc_service.lamport_clock import LamportClock        # noqa: E402


# ============================================================
# LAMPORT CLOCK — server instance
# Shared across all RPC handler threads (protected by Lock)
# ============================================================
server_clock = LamportClock(initial_time=0)


# ============================================================
# DATASET — Load all three CSV files from existing Dataset/
# ============================================================

DATASET_DIR = os.path.join(PROJECT_ROOT, "Dataset")


def load_food_data() -> pd.DataFrame:
    """
    Load and concatenate Breakfast.csv, Lunch.csv, Dinner.csv.
    Column names are lower-cased and stripped for robust lookup.
    """
    frames = []
    files = ["Breakfast.csv", "Lunch.csv", "Dinner.csv"]

    for filename in files:
        filepath = os.path.join(DATASET_DIR, filename)
        if os.path.exists(filepath):
            try:
                df = pd.read_csv(filepath)
                # Normalise column names: strip whitespace, lowercase
                df.columns = df.columns.str.strip().str.lower()
                frames.append(df)
                print(f"[SERVER] Loaded {filename} ({len(df)} rows)")
            except Exception as exc:
                print(f"[SERVER] ERROR loading {filename}: {exc}")
        else:
            print(f"[SERVER] WARNING: {filepath} not found")

    if not frames:
        print("[SERVER] WARNING: No dataset files loaded!")
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True)

    # Convert all numeric columns safely
    for col in ["calories", "protein", "carbs", "fat", "fiber", "calcium", "iron"]:
        if col in combined.columns:
            combined[col] = pd.to_numeric(combined[col], errors="coerce").fillna(0)

    return combined


FOOD_DATA = load_food_data()


# ============================================================
# HELPER — look up a food row by name (case-insensitive)
# ============================================================

def find_food(meal_name: str) -> dict | None:
    """
    Search FOOD_DATA for a row whose food_name matches meal_name
    (case-insensitive, partial match allowed).

    Returns a dict with calories/protein/carbs/fat, or None if not found.
    """
    if FOOD_DATA.empty:
        return None

    # The CSVs use the column 'food_name' (verified by inspection)
    if "food_name" not in FOOD_DATA.columns:
        return None

    search = meal_name.strip().lower()
    mask = FOOD_DATA["food_name"].astype(str).str.strip().str.lower() == search
    matches = FOOD_DATA[mask]

    # Fallback: partial contains match
    if matches.empty:
        mask = FOOD_DATA["food_name"].astype(str).str.lower().str.contains(
            search, na=False
        )
        matches = FOOD_DATA[mask]

    if matches.empty:
        return None

    row = matches.iloc[0]

    def val(col: str) -> float:
        if col in row.index:
            v = row[col]
            try:
                return 0.0 if pd.isna(v) else float(v)
            except (ValueError, TypeError):
                return 0.0
        return 0.0

    return {
        "calories": val("calories"),
        "protein":  val("protein"),
        "carbs":    val("carbs"),
        "fat":      val("fat"),
    }


# ============================================================
# gRPC SERVICE IMPLEMENTATION
# ============================================================

class MealService(meal_service_pb2_grpc.MealServiceServicer):
    """
    Implements the MealService RPC defined in meal_service.proto.

    Distributed Computing concepts demonstrated:
      - Remote Procedure Call (RPC): client calls GetMealNutrition
        as if it were a local function, but it executes on this server.
      - Protocol Buffers: messages are serialized/deserialized
        automatically by the generated pb2 code.
      - Lamport Clock: server updates its clock on receive,
        then ticks again before sending the response — creating a
        globally consistent ordering of distributed events.
    """

    def GetMealNutrition(self, request, context):
        """
        Handle an incoming MealRequest RPC call.

        Steps:
          1. Receive client Lamport timestamp → update server clock.
          2. Search dataset for the requested food.
          3. Tick server clock for the response event.
          4. Return MealResponse with nutrition + server timestamp.
        """

        # --------------------------------------------------------
        # STEP 1 — Update Lamport clock on RECEIVE
        # Rule: C_server = max(C_server, C_client) + 1
        # --------------------------------------------------------
        receive_time = server_clock.receive(request.lamport_timestamp)

        print()
        print("-" * 60)
        print("[SERVER] <- Request RECEIVED")
        print(f"[SERVER]   Meal name      : {request.meal_name}")
        print(f"[SERVER]   Client Lamport : {request.lamport_timestamp}")
        print(f"[SERVER]   Server Lamport : {receive_time}  "
              f"(= max(prev, {request.lamport_timestamp}) + 1)")

        # --------------------------------------------------------
        # STEP 2 — Look up nutrition data
        # --------------------------------------------------------
        food = find_food(request.meal_name)

        # --------------------------------------------------------
        # STEP 3 — Tick clock for the SEND (response) event
        # --------------------------------------------------------
        response_time = server_clock.tick()
        print(f"[SERVER]   Send Lamport   : {response_time}  (tick after search)")

        # --------------------------------------------------------
        # STEP 4 — Build and return response
        # --------------------------------------------------------
        if food is None:
            print(f"[SERVER]   Status         : NOT_FOUND")
            print("-" * 60)
            return meal_service_pb2.MealResponse(
                meal_name         = request.meal_name,
                calories          = 0.0,
                protein           = 0.0,
                carbs             = 0.0,
                fat               = 0.0,
                lamport_timestamp = response_time,
                status            = "NOT_FOUND",
            )

        print(f"[SERVER]   Status         : SUCCESS")
        print(f"[SERVER]   Calories       : {food['calories']}")
        print(f"[SERVER]   Protein        : {food['protein']} g")
        print(f"[SERVER]   Carbs          : {food['carbs']} g")
        print(f"[SERVER]   Fat            : {food['fat']} g")
        print("-" * 60)

        return meal_service_pb2.MealResponse(
            meal_name         = request.meal_name,
            calories          = food["calories"],
            protein           = food["protein"],
            carbs             = food["carbs"],
            fat               = food["fat"],
            lamport_timestamp = response_time,
            status            = "SUCCESS",
        )


# ============================================================
# SERVER STARTUP
# ============================================================

def serve():
    """Start the gRPC server and block until terminated."""

    print()
    print("=" * 70)
    print("  STARTING MEAL PLANNER gRPC SERVER  --  Experiment 3")
    print("=" * 70)

    # Verify Lamport clock before starting
    _verify_lamport_clock()

    # Create gRPC server with a thread pool
    # ThreadPoolExecutor allows handling multiple concurrent RPCs
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=10)
    )

    # Register the MealService implementation
    meal_service_pb2_grpc.add_MealServiceServicer_to_server(
        MealService(),
        server
    )

    # Bind to all interfaces on port 50051 (insecure for lab use)
    server.add_insecure_port("[::]:50051")

    server.start()

    print(f"[SERVER] Server started successfully")
    print(f"[SERVER] Running on port 50051")
    print(f"[SERVER] Initial Lamport Clock : {server_clock.now()}")
    print(f"[SERVER] Dataset rows loaded   : {len(FOOD_DATA)}")
    print(f"[SERVER] Waiting for client connections ...")
    print("=" * 70)

    # Block here — server runs until Ctrl+C or process kill
    server.wait_for_termination()


# ============================================================
# VERIFY LAMPORT CLOCK (called before serving)
# ============================================================

def _verify_lamport_clock():
    """Quick sanity check of Lamport clock logic."""
    clock = LamportClock(initial_time=0)
    t1 = clock.tick()           # Local event → 1
    t2 = clock.receive(10)      # Receive timestamp 10 → max(1,10)+1 = 11
    t3 = clock.tick()           # Next local event → 12

    assert t1 == 1,  f"Lamport tick() failed: expected 1, got {t1}"
    assert t2 == 11, f"Lamport receive(10) failed: expected 11, got {t2}"
    assert t3 == 12, f"Lamport tick() after receive failed: expected 12, got {t3}"

    print("[SERVER] [OK] Lamport clock verification passed")
    print(f"[SERVER]   Event 1 (tick)          -> {t1}")
    print(f"[SERVER]   Receive timestamp 10    -> {t2}")
    print(f"[SERVER]   Next local event (tick) -> {t3}")


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    serve()
